rspec-tst-rails/hotwire-test-app-main/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'

  resources :courses

  resources :users do
    member do
      post :change_status
    end
  end

  resources :user_courses, only: [:index] do
    member do
      post :like
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'welcome#index'
end

rspec-tst-rails/hotwire-test-app-main/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rspec-tst-rails/hotwire-test-app-main/app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  enum status: { draft: 0, published: 1 }
end

rspec-tst-rails/hotwire-test-app-main/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_courses, dependent: :destroy
  has_many :courses, through: :user_courses

  validates :name, presence: true

  def name_and_email
    "#{name} - #{email}"
  end
end

rspec-tst-rails/hotwire-test-app-main/app/models/user_course.rb
# frozen_string_literal: true

class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

rspec-tst-rails/hotwire-test-app-main/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

rspec-tst-rails/hotwire-test-app-main/app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    search_params = params[:title].blank? ? {} : "title LIKE '%#{params[:title]}%'"
    @courses = Course.where(search_params)
  end

  # GET /courses/1 or /courses/1.json
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :video_url)
  end
end

rspec-tst-rails/hotwire-test-app-main/app/controllers/user_courses_controller.rb
# frozen_string_literal: true

class UserCoursesController < ApplicationController
  def index
    @user_courses = UserCourse.all
  end

  def like
    user_course = UserCourse.find(params[:id]).increment!(:likes)
    # redirect_to user_courses_path
    render user_course
  end
end

rspec-tst-rails/hotwire-test-app-main/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @pagy, @users = pagy(User.all, items: 5)
  end

  # GET /users/1 or /users/1.json
  def show
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @users = User.all
    @user.destroy!

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'User was successfully destroyed.' }
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_status
    @users = User.all
    @user = @users.find(params[:id])
    @user.update!(active: !@user.active)

    redirect_to users_url

    # respond_to do |format|
    #   formt.html { redirect_to users_url }
    #   format.turbo_stream
    # end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

rspec-tst-rails/hotwire-test-app-main/app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

rspec-tst-rails/hotwire-test-app-main/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

rspec-tst-rails/hotwire-test-app-main/app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

rspec-tst-rails/hotwire-test-app-main/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

rspec-tst-rails/hotwire-test-app-main/app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

rspec-tst-rails/hotwire-test-app-main/app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Title:</strong>
    <%= course.title %>
  </p>

  <p>
    <strong>Video url:</strong>
    <%= course.video_url %>
  </p>

</div>

rspec-tst-rails/hotwire-test-app-main/app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :video_url, style: "display: block" %>
    <%= form.text_field :video_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Courses</h1>

<%= form_with(url: courses_path, method: :get, data: { turbo_frame: "results", turbo_action: "advance" }) do |f| %>
  <div>
    <%= f.search_field :title, placeholder: "Course name", value: params[:title] %>
    <%= f.submit "Search" %>
  </div>
  <hr>
<% end %>

<%= turbo_frame_tag "results" do %>
  <div id="courses">
    <% @courses.each do |course| %>
      <%= render course %>
      <p>
        <%= link_to "Show this course", course %>
      </p>
      <hr>
    <% end %>
  </div>
<% end %>


<%= link_to "New course", new_course_path %>

rspec-tst-rails/hotwire-test-app-main/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>

  <%= button_to "Destroy this course", @course, method: :delete %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |type, message| %>
    <div>
      <%= message %>
    </div>
  <% end %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireTestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag :flash_messages do %>
      <%= render "layouts/flash_messages" %>
    <% end %>

    <%= yield %>
  </body>
</html>

rspec-tst-rails/hotwire-test-app-main/app/views/user_courses/_user_course.html.erb
<%= turbo_frame_tag dom_id(user_course) do %>
  <p><%= "Usuário: #{user_course.user.name}"%><%= link_to '(ver)', user_path(user_course.user), data: { turbo_frame: "_top" }%> </p>
  <p><%= "Email: #{user_course.user.email}"%> </p>
  <p><%= "Curso:#{user_course.course.title}"%> <%= link_to '(ver)', course_path(user_course.course), data: { turbo_frame: "_top" } %></p>
  <p><%= "Url:#{user_course.course.video_url}"%> </p>

  <p>Qtd. de likes: <strong><%= user_course.likes %></strong></p>
  <p><%= Time.now.strftime("%H:%M:%S") %></p>

  <%= button_to 'Like!', like_user_course_path(user_course), method: :post %>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/user_courses/index.html.erb
<% @user_courses.each do |user_course| %>
  <%= render user_course %>
  <hr>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/___change_status.turbo_stream.erb
<%= turbo_stream.update :users_status_count do %>
  <%= render "users_status_count" %>
<% end %>

<%= turbo_stream.replace "change_status_button_#{dom_id(@user)}" do %>
  <%= render "change_status_button", user: @user %>
<% end %>

<%= turbo_stream.replace dom_id(@user) do %>
  <%= render "user", user: @user %>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/_change_status_button.html.erb
<%= content_tag(:div, id: "change_status_button_#{dom_id(user)}") do %>
  <p>
    <% user_status_label = user.active ? "Inactivate!" : "Activate!" %>
    <%= button_to user_status_label, change_status_user_path(user) %>
  </p>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Ativo?:</strong>
    <%= user.active ? "Sim" : "Não" %>
  </p>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/users/_users_status_count.html.erb
<h2>
  <%= "Actives: #{User.where(active: true).count} / Inactives: #{User.where(active: false).count} " %>
</h2>

rspec-tst-rails/hotwire-test-app-main/app/views/users/destroy.turbo_stream.erb
<%= turbo_stream.update :users_status_count do %>
  <%= render "users_status_count" %>
<% end %>

<%= turbo_stream.remove "user_container_#{dom_id(@user)}" %>

<%= turbo_stream.update :flash_messages do %>
  <%= render "layouts/flash_messages" %>
<% end %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<%= content_tag(:div, id: :users_status_count, "data-turbo-permanent": '') do %>
  <%= render "users_status_count" %>
<% end %>

<div id="users">
  <div>
    <% @users.each do |user| %>
      <div>
        <%= render user %>
        <p>
          <%= link_to "Show this user", user, target: "_top" %>
        </p>

        <%= link_to "Destroy this user", user, data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>

        <%= render "change_status_button", user: %>

        <hr>
      </div>
    <% end %>

    <% if @pagy.next %>
      <%= turbo_frame_tag "show_users_per_page_#{@pagy.next}", src: users_path(page: @pagy.next), loading: :lazy do %>
        <p>Waiting...</p>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to "New user", new_user_path %>

rspec-tst-rails/hotwire-test-app-main/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= content_tag(:div, id: :users_status_count, "data-turbo-permanent": '') do %>
  <%= render "users_status_count" %>
<% end %>

<%= turbo_frame_tag "show" do %>
  <%= render @user %>
<% end %>

<%= render "change_status_button", user: @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%#= button_to "Destroy this user", @user, method: :delete, data: { turbo_confirm: "Are you sure?", turbo: false } %>
  <%= button_to "Destroy this user", @user, method: :delete, data: { turbo: false } %>
</div>

rspec-tst-rails/hotwire-test-app-main/app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%#= link_to 'Usuários', users_path, data: { turbo: false } %> <br>
<%= link_to 'Usuários', users_path %> <br>
<%= link_to 'Cursos', courses_path %> <br>
<%= link_to 'Usuários x Cursos', user_courses_path %> <br>